# HTTP Server
server:
  port: 12032  # HTTP (Tomcat) port

spring:
  application:
    name: ts-order-other-service
  data:
    mongodb:
      host: ts-order-other-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

#  rabbitmq:
#    host: rabbitmq
#    listener:
#      retry:
#        enabled: false
#        max-attempts: 1
#    template:
#      retry:
#        enabled: false
#        max-attempts: 1
#  cloud:
#    stream:
#      bindings:
#        output:
#          # group: ts-return-cancel
#          destination: ts-order-other-exchange
#          contentType: application/json
#          binder: rabbit
#        input:
#          group: ts-order-other-service
#          destination: ts-order-other-exchange
#          contentType: application/json
#          binder: rabbit

swagger:
  controllerPackage: other.controller