kubectl autoscale deployment ts-assurance-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-auth-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-basic-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-config-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-consign-price-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-consign-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-contacts-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-execute-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-food-map-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-food-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-inside-payment-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-order-other-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-order-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-payment-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-preserve-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-price-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-route-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-seat-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-security-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-station-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-ticketinfo-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-train-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-travel-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-travel2-service -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-ui-dashboard -n default --min=1 --max=8 --cpu-percent=80
kubectl autoscale deployment ts-user-service -n default --min=1 --max=8 --cpu-percent=80